name: Deploy Admin App to Staging Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to staging
        env:
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          echo "PRIVATE_SSH_KEY: $PRIVATE_SSH_KEY"
          echo "SERVER_IP: $SERVER_IP"
          echo "REMOTE_PORT: $REMOTE_PORT"
          echo "SERVER_USER: $SERVER_USER"
          echo "REMOTE_TARGET: $REMOTE_TARGET"
          
          mkdir -p ~/.ssh/
          echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p $REMOTE_PORT $SERVER_IP >> ~/.ssh/known_hosts
          scp -r -P $REMOTE_PORT .output/* $SERVER_USER@$SERVER_IP:$REMOTE_TARGET
          ssh -p $REMOTE_PORT $SERVER_USER@$SERVER_IP "pm2 reload adminapp --update-env"
          echo "Admin App Staging Deployment completed."